# Generated by Django 6.0.3 on 2026-04-10 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rename_amount_payment_amount_paisa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount_Paisa',
            new_name='amount',
        ),
    ]
