# Generated by Django 6.0.2 on 2026-03-11 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sessionrecommendation',
            options={'ordering': ['rank']},
        ),
        migrations.RenameField(
            model_name='song',
            old_name='duration',
            new_name='duration_seconds',
        ),
        migrations.RemoveField(
            model_name='mood',
            name='emotional_value',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='emotional_value',
        ),
        migrations.AddField(
            model_name='mood',
            name='energy',
            field=models.FloatField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mood',
            name='valence',
            field=models.FloatField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='energy',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='valence',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(related_name='songs', to='app.artist'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Tenant Admin'), ('user', 'User')], default='user', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='memory',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.tenant'),
        ),
        migrations.AddField(
            model_name='moodsession',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersonginteraction',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.tenant'),
            preserve_default=False,
        ),
    ]
