# Generated by Django 6.0.2 on 2026-03-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='memory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='song',
            name='mood',
        ),
        migrations.AddField(
            model_name='song',
            name='mood',
            field=models.ManyToManyField(related_name='songs', to='app.mood'),
        ),
    ]
