# Generated by Django 6.0.2 on 2026-03-14 19:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_artist_tenant_alter_sessionrecommendation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersonginteraction',
            unique_together={('tenant', 'user', 'song', 'mood')},
        ),
        migrations.RemoveField(
            model_name='song',
            name='moods',
        ),
        migrations.AddField(
            model_name='moodsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='source',
            field=models.CharField(default='spotify', max_length=50),
        ),
        migrations.AddField(
            model_name='usersonginteraction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tenant'),
        ),
        migrations.AlterField(
            model_name='song',
            name='play_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersonginteraction',
            name='play_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersonginteraction',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='sessionrecommendation',
            unique_together={('session', 'rank'), ('session', 'song')},
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['valence', 'energy', 'is_available'], name='app_song_valence_5aa1ef_idx'),
        ),
        migrations.AddIndex(
            model_name='usersonginteraction',
            index=models.Index(fields=['tenant', 'user'], name='app_userson_tenant__45bc57_idx'),
        ),
        migrations.AddIndex(
            model_name='usersonginteraction',
            index=models.Index(fields=['song'], name='app_userson_song_id_b987f6_idx'),
        ),
    ]
