# Generated by Django 6.0.2 on 2026-03-04 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_memory_options_song_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodsession',
            name='songs',
        ),
        migrations.AlterField(
            model_name='song',
            name='external_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='SessionRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='app.moodsession')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.song')),
            ],
            options={
                'unique_together': {('session', 'song')},
            },
        ),
    ]
