# Generated by Django 6.0.3 on 2026-03-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_usersonginteraction_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodsession',
            name='input_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moodsession',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
