# Generated by Django 6.0.3 on 2026-04-18 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_premium_until_alter_profile_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='memory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='moodsession',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sessionrecommendation',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='song',
            name='app_song_valence_5aa1ef_idx',
        ),
        migrations.RemoveIndex(
            model_name='usersonginteraction',
            name='app_userson_tenant__45bc57_idx',
        ),
        migrations.RemoveIndex(
            model_name='usersonginteraction',
            name='app_userson_song_id_b987f6_idx',
        ),
        migrations.AlterUniqueTogether(
            name='sessionrecommendation',
            unique_together={('session', 'rank')},
        ),
        migrations.RemoveField(
            model_name='artist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mood',
            name='description',
        ),
        migrations.AddField(
            model_name='song',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.song'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='premium_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='app.tenant'),
        ),
        migrations.AlterField(
            model_name='song',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invite',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tenant'),
        ),
        migrations.RemoveField(
            model_name='song',
            name='last_synced',
        ),
        migrations.RemoveField(
            model_name='song',
            name='source',
        ),
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together={('email', 'tenant')},
        ),
    ]
